// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Player : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.player_Move;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grab
        {
            get
            {
                return SteamVR_Actions.player_Grab;
            }
        }
        
        public virtual SteamVR_Action_Boolean Cast
        {
            get
            {
                return SteamVR_Actions.player_Cast;
            }
        }
        
        public virtual SteamVR_Action_Boolean Run
        {
            get
            {
                return SteamVR_Actions.player_Run;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.player_Teleport;
            }
        }
    }
}
